---
logging:
  level:
    org:
      springframework:
        transaction:
          nodeValue: INFO
          interceptor: TRACE
        orm:
          jpa:
            nodeValue: INFO
            JpaTransactionManager: DEBUG
        web:
          servlet:
            DispatcherServlet: DEBUG

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: "true"
        show_sql: "true"
  sql:
    init:
      mode: always
---
spring:
  datasource:
    username: shareit
    url: jdbc:postgresql://localhost:5432/shareit
    driverClassName: org.postgresql.Driver
    password: shareit
---
spring:
  config:
    activate:
      on-profile: ci,test
  datasource:
    username: test
    url: jdbc:h2:mem:shareit
    driverClassName: org.h2.Driver
    password: test
  h2:
    console.enabled: true
